### ISSUE TITLE
user id never gets added to jwt payload when signing up

### ISSUE THREAD

**Issue by reubengt** [fac19/week7-hihi#37]
https://github.com/fac19/week7-hihi/blob/68325ba5d03c75eb9b636ebb894a38d0f44504b1/handlers/users-handler.js#L27-L32

newUser here is res.rows from the database, which for an insert statement is [] empty array.
so newUser.id will always be undefined. what you'd need to do is create the user, then select the user.

is this a stretch goal functionality to be able to make authenticated requests as soon as you create a user?

**Comment by oliverjam** [comment]
The easiest way to fix this is to add `RETURNING id` to the end of the create user SQL query. That makes the INSERT return the id column of the newly created row

**Comment by jackherizsmith** [comment]
newUser is undefined on line 29 of usersHandler so accesstoken can't be attached
    - try `
    .then(() => {
      return getUser(username)
    })` in users-model.addUser

**Comment by oliverjam** [comment]
You shouldn't need to make another DB query to get the thing you just inserted, that's what the RETURNING keyword is for. E.g. something like `INSERT INTO users (username, password, cohort)VALUES($1, $2, $3) RETURNING id, username, cohort;`
