### ISSUE TITLE
getMultipleUsersById function has a cool map to create a list that looks like [$1,$2,$3,$4,$5]. but it's poorly named and not commented and i guarantee you'll forget what this does.

### ISSUE THREAD

**Issue by reubengt** [fac19/week7-hihi#41]
https://github.com/fac19/week7-hihi/blob/68325ba5d03c75eb9b636ebb894a38d0f44504b1/model/users-model.js#L41-L46

the id's parameter comes from junctionModel.getUserFromBook . 

lines 42 to 44 are rewriting this list with a list of $1 to $x.. if there are 5 elements this will be [$1,$2,$3,$4,$5]

this is to act as sql variables(i forgot what theyre actually called) to prevent injection.
but calling this variable list, and calling the map callback arguments e and I are not great code practice 😅

I would comment what this is doing, and perhaps change "list" to "sqlVariableList", and comment above the map function what its output would be. 
took me 15 mins to figure out what was going on here haha

**Comment by jackherizsmith** [comment]
is user input being inserted into the SQL query in `users-model.js` line 45?

**Comment by reubengt** [comment]
good point @jackherizsmith it isnt! things are going from the database back into the database. so the $ sign substitutions stuff is probably overkill
